# String Methods Demonstration in Python

name: str = "muhammad asif"
print("Original:", name)

print("capitalize():", name.capitalize())
print("casefold():", name.casefold())
print("center(20, '*'):", name.center(20, '*'))
print("count('a'):", name.count('a'))
print("encode():", name.encode())
print("endswith('if'):", name.endswith("if"))
print("expandtabs(4):", "muhammad\tasif".expandtabs(4))
print("find('asif'):", name.find("asif"))
print("format():", "My name is {}".format(name))
print("format_map():", "{first} {last}".format_map({"first": "Muhammad", "last": "Asif"}))
print("index('asif'):", name.index("asif"))
print("isalnum():", name.isalnum())
print("isalpha():", name.isalpha())
print("isascii():", name.isascii())
print("isdecimal():", "123".isdecimal())
print("isdigit():", "123".isdigit())
print("isidentifier():", "myVar".isidentifier())
print("islower():", name.islower())
print("isnumeric():", "123".isnumeric())
print("isprintable():", name.isprintable())
print("isspace():", "   ".isspace())
print("istitle():", "Muhammad Asif".istitle())
print("isupper():", "ASIF".isupper())
print("join():", "-".join(["Muhammad", "Asif"]))
print("ljust(20, '-'):", name.ljust(20, '-'))
print("lower():", name.lower())
print("lstrip():", "   asif   ".lstrip())
print("maketrans() + translate():", "abc".translate(str.maketrans("abc", "123")))
print("partition(' '):", name.partition(" "))
print("removeprefix('muh'):", name.removeprefix("muh"))
print("removesuffix('if'):", name.removesuffix("if"))
print("replace('asif','ali'):", name.replace("asif", "ali"))
print("rfind('a'):", name.rfind("a"))
print("rindex('a'):", name.rindex("a"))
print("rjust(20, '-'):", name.rjust(20, '-'))
print("rpartition(' '):", name.rpartition(" "))
print("rsplit(' '):", name.rsplit(" "))
print("rstrip():", "   asif   ".rstrip())
print("split(' '):", name.split(" "))
print("splitlines():", "line1\nline2".splitlines())
print("startswith('mu'):", name.startswith("mu"))
print("strip():", "   asif   ".strip())
print("swapcase():", "Muhammad Asif".swapcase())
print("title():", name.title())
print("upper():", name.upper())
print("zfill(15):", name.zfill(15))
