first_name = "Muhammad"
last_name = "Asif"
print("Full Name:", first_name + " " + last_name)
print("First Name:", first_name)
print("Last Name:", last_name)
print("First Name Length:", len(first_name))
print("Last Name Length:", len(last_name))
print("Total Length:", len(first_name) + len(last_name))
print("Uppercase Full Name:", (first_name + " " + last_name).upper())
print("Lowercase Full Name:", (first_name + " " + last_name).lower())
print("Title Case Full Name:", (first_name + " " + last_name).title())
print("Is First Name Alphabetic?:", first_name.isalpha())
print("Is Last Name Alphabetic?:", last_name.isalpha())
print("First Name starts with 'M'?:", first_name.startswith("M"))
print("Last Name ends with 'f'?:", last_name.endswith("f"))
print("Index of 'a' in First Name:", first_name.index("a"))
print("Count of 'a' in Last Name:", last_name.count("a"))
print("Reversed Full Name:", (last_name + " " + first_name))
print("Reversed Full Name:", (last_name + " " + first_name)[::-1])
print("Formatted Full Name: {} {}".format(first_name, last_name))
print(f"Formatted Full Name: {first_name} {last_name}")
print("Concatenated Full Name:", first_name + " " + last_name)
print("First Name with spaces replaced by underscores:", first_name.replace(" ", "_"))
print("Last Name with spaces replaced by underscores:", last_name.replace(" ", "_"))
print("First Name Split into Characters:", list(first_name))
print("Last Name Split into Characters:", list(last_name))
