print("Hello World!")
print("My name is Muhammad Asif.")
print("Welcome to the Python Programming Language.")
print("This is my first Python program.")
print("I am excited to learn more about Python!")

print()

print("Hello World!")
print('hello world!')
print("""Hello World! """)
print('''Hello World! ''')
print("Hello" + " " + "World!")
print("Hello" , "World!")
print("Hello" * 3)
print("Hello " * 3 + "World!")
